# Generated by Django 4.2.6 on 2023-10-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega', '0003_alter_clientes_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
