# Generated by Django 4.2.6 on 2023-10-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega', '0004_alter_clientes_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locales',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='locales',
            name='nombre',
        ),
        migrations.AddField(
            model_name='locales',
            name='altura',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
